apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: petclinic
spec:
  selector:
    app: genai-service
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/spring-petclinic/genai-service:${VERSION}
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_SERVER_URL
              value: http://discovery-server:8761/eureka/
      imagePullSecrets:
        - name: ecr-secret