apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vets-db-mysql
  namespace: spring-petclinic
spec:
  selector:
    matchLabels:
      app: vets-db-mysql
  serviceName: vets-db-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: vets-db-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vets-db-mysql
  namespace: spring-petclinic
spec:
  selector:
    app: vets-db-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
